# Generated by Django 4.1 on 2022-10-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDeveloper', models.CharField(default='', max_length=50)),
                ('gameName', models.CharField(max_length=70)),
                ('gameGenre', models.CharField(max_length=30)),
                ('gameRelease', models.DateField()),
                ('gameScore', models.FloatField()),
                ('gameReview', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='upcomingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcomingName', models.CharField(max_length=70)),
                ('upcomingRelease', models.DateField()),
                ('upcomingsWallpaper', models.ImageField(null=True, upload_to='games')),
            ],
        ),
    ]
