# Generated by Django 4.1 on 2022-10-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameGenre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
